apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: poc-websocket
manifests:
  rawYaml:
    - deploy/deploy.yaml
    - deploy/service.yaml
build:
  artifacts:
  - image: poc-websocket
deploy:
  docker:
    images: [poc-websocket]
portForward:
- resourceType: service
  resourceName: poc-websocket
  port: 80