apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: poc-websocket
manifests:
  rawYaml:
    - manifests/deploy.yaml
    - manifests/service.yaml
deploy:
  docker:
    images: [poc-websocket]
portForward:
  - resourceType: service
    resourceName: poc-websocket
    port: 80
build:
  artifacts:
    - image: poc-websocket
