# apiVersion: v1
# kind: Service
# metadata:
#   name: poc-websocket
#   namespace: poc-websocket
# spec:
#   selector:
#     app: poc-websocket
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: poc-websocket
  namespace: poc-websocket
spec:
  selector:
    app: poc-websocket
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
  sessionAffinity: ClientIP