apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay
  namespace: poc-websocket
spec:
  action: delay # the specific chaos action to inject
  mode: all # the mode to run chaos action; supported modes are one/all/fixed/fixed-percent/random-max-percent
  selector: # pods where to inject chaos actions
    namespaces:
      - poc-websocket
    labelSelectors:
      'app': 'poc-websocket' # the label of the pod for chaos injection
  delay:
    latency: '10s'
  duration: '10h'