kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: chaos-mesh
  name: account-chaos-mesh-manager-vqqem

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: chaos-mesh
  name: role-chaos-mesh-manager-vqqem
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["chaos-mesh.org"]
  resources: [ "*" ]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-chaos-mesh-manager-vqqem
  namespace: chaos-mesh
subjects:
- kind: ServiceAccount
  name: account-chaos-mesh-manager-vqqem
  namespace: chaos-mesh
roleRef:
  kind: Role
  name: role-chaos-mesh-manager-vqqem
  apiGroup: rbac.authorization.k8s.io
